runner/api/urls.py
# -*- coding: utf-8 -*-
"""
Author: Philippe 'paHpa' Vivien <philippe.vivien@nerim.com>

Copyright: Nerim, 2015
"""
from __future__ import unicode_literals

from django.conf.urls import url, include

from rest_framework import routers

from .views import  JuridictionViewSet

router = routers.DefaultRouter(trailing_slash=False)
router.register(r'juridt', JuridictionViewSet)

urlpatterns = [
    url(r'^', include(router.urls)),
    #url(r'^docs/', include('rest_framework_swagger.urls')),
]

runner/blacklist/local/urls.py
/home/tony/workspace/Developpement/virtualenvs/projet/blacklist/blacklist/urls.py

runner/blacklist/urls.py
# -*- coding: utf-8 -*-
"""
Author: tony payet

Copyright: Nerim, 2015
"""
from __future__ import unicode_literals
from django.contrib.auth.decorators import login_required

from django.conf.urls import patterns, url

from blacklist.views import  blacklist_list, upload_file


urlpatterns = patterns('',
    url(r'^jsonblacklist_list/$', login_required(blacklist_list.as_view()), name='blacklist_list'),
    url(r'^csv/$', login_required(upload_file) ,name='csv'),  
)

runner/runner/urls.py
# -*- coding: utf-8 -*-

# Copyright (C) 2014 Nerim (Philippe 'paHpa' Vivien)

from django.conf.urls import (  # noqa
    patterns, include, url,
)
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.core.exceptions import ImproperlyConfigured
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required



from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'runner.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
#    url(r"^account/", include("account.urls")),

    #pinax account
    url(r"^accounts/", include("account.urls")),
    
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')), 
    url(r'^admin/', include(admin.site.urls)),
#    url(r'^example/', 'example.views.index'),   

    url(r'^blacklist/', include('blacklist.urls' , namespace='blacklist', app_name='blacklist')),
  
    url(r'^api/', include('api.urls', namespace='api')),


)

# PAHPA : LOAD URL 
#print "** PAHPA ** loadind url"
from django.conf import settings

#TEST DJANGO-REST
if 'rest_framework' in settings.INSTALLED_APPS:

    from rest_framework.authtoken import views
    from account.views import SettingsView
    
    urlpatterns += patterns('',
        url(r'^api-auth/', include('rest_framework.urls',
                               namespace='rest_framework')),
#        url(r'^api-token-auth/', views.obtain_auth_token), 

        #si utilisation djoser account (en test)
        #url(r'^auth/', include('djoser.urls')),

        #mapping pinax 'account'
        url(r"^accounts/profile/$", SettingsView.as_view(), name="account_settings"),
    )

if 'adminactions' in settings.INSTALLED_APPS:
    from django.contrib.admin import site
    import adminactions.actions as actions
    actions.add_to_site(site)

    urlpatterns += patterns('',
    (r'^adminactions/', include('adminactions.urls')),
    )
   
if 'xadmin' in settings.INSTALLED_APPS:
    import xadmin
    xadmin.autodiscover()
    
    urlpatterns += patterns('',
        url(r'^xadmin/', include(xadmin.site.urls)),
    )

if 'imagestore' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        url(r'^gallery/', include('imagestore.urls', namespace='imagestore')),
    )
    
if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        url(r'^rosetta/', include('rosetta.urls')),
    )

if 'helpdesk' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        url(r'helpdesk/', include('helpdesk.urls')),
    )

if 'wkhtmltopdf' in settings.INSTALLED_APPS:
    from wkhtmltopdf.views import PDFTemplateView
    urlpatterns += patterns('',
        url(r'^pdf/$', PDFTemplateView.as_view(template_name='billing/template.html',filename='my_pdf.pdf'), name='pdf'),
    )

#if 'docs' in settings.INSTALLED_APPS:
#    urlpatterns += patterns('',
#        url(r'^docs/', include('docs.urls')),
#    )

if 'sphinxdoc' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        url(r'^docs/', include('sphinxdoc.urls')),
    )

if 'haystack' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        url(r'^search/', include('haystack.urls'))
    )

#
#if 'dajaxice' in settings.INSTALLED_APPS:
#    from dajaxice.core import dajaxice_autodiscover, dajaxice_config
#    dajaxice_autodiscover()
#
#    urlpatterns += patterns('',
#        url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),
#    )

#if 'admin_tools' in settings.INSTALLED_APPS:
#    urlpatterns += patterns('',
#        url(r'^admin_tools/', include('admin_tools.urls')),
#    )
#
if 'forms_builder.forms' in settings.INSTALLED_APPS:
    import forms_builder.forms.urls
    urlpatterns += patterns('',
        url(r'^forms/', include(forms_builder.forms.urls)),
    )

if 'demo' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        url(r'^demo/', include('demo.urls')),
    )

if settings.DEBUG:
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns += patterns('',
            url(r'^__debug__/', include(debug_toolbar.urls)),
        )

    urlpatterns += patterns('',
                    (r'^' + settings.MEDIA_URL[1:] + '(?P<path>.*)$', 'django.views.static.serve',
                    {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
                    )
    urlpatterns += patterns('django.contrib.staticfiles.views',
        url(r'^static/(?P<path>.*)$', 'serve'),
    )
else:
# mettre en place un flag DJNGO_SERVE_STATIC
    urlpatterns += patterns('',
                    (r'^' + settings.MEDIA_URL[1:] + '(?P<path>.*)$', 'django.views.static.serve',
                    {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
                    )
    urlpatterns += patterns('django.contrib.staticfiles.views',
        url(r'^static/(?P<path>.*)$', 'serve'),
    )
    
handler404 = 'runner.views.my_custom_404_view'

runner/blacklist/local/models.py
/home/tony/workspace/Developpement/virtualenvs/projet/blacklist/blacklist/models.py

runner/blacklist/models.py
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.contrib.auth.models import User



@python_2_unicode_compatible
class Blacklist(models.Model):
    email = models.CharField(max_length=200)
    type_blacklist = models.CharField(max_length=200)
    user = models.ForeignKey(User)    
    
    class Meta:
        verbose_name = 'Blacklist'
    
    def __str__(self):              # __unicode__ on Python 2
        return self.email
        

runner/blacklist/local/views.py
/home/tony/workspace/Developpement/virtualenvs/projet/blacklist/blacklist/views.py

runner/blacklist/views.py
# -*- coding: utf-8 -*-
"""
Author: Philippe 'paHpa' Vivien <philippe.vivien@nerim.com>
Author: Tony Payet <tony@nerim.com>

Copyright: Nerim, 2014
"""
from __future__ import unicode_literals

from django.contrib.auth.decorators import login_required , user_passes_test
from django.utils.decorators import method_decorator
from django.shortcuts import render
from django.views.generic import TemplateView
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect, StreamingHttpResponse,Http404
from django_datatables_view.base_datatable_view import BaseDatatableView
from django.forms.formsets import formset_factory
from django.forms.models import inlineformset_factory
from django.views.decorators.csrf import csrf_exempt
from django.conf import settings
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.utils.encoding import python_2_unicode_compatible
from django.template import Context, loader
# Create your views here.

from blacklist.models import Blacklist
from runner.utils.logger import logger

import json

from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.shortcuts import render_to_response
from django.contrib.auth.models import User
import csv  


"""
retourne la data blacklist 

""" 

class blacklist_list(BaseDatatableView):
    
    model = Blacklist

    columns = ['id','type_blacklist','email','user_id']
    order_columns = ['id','type_blacklist','email','user_id']
    
    def get_context_data(self, *args, **kwargs):
        user=User.objects.get(username=self.request.user) 
        context = super(blacklist_list, self).get_context_data(**kwargs)
        data=context['data']
        data=[elem for elem in data if elem['user_id'] == user.id]

        for a in data:
            idrecup=a['id']
            a['DT_RowId']=idrecup 
            a['user_id']=str(a['user_id'] )

        blacklist=Blacklist.objects.filter(user_id=user.id )
 
        ret ={
                       'data':data,
                       'recordsTotal': blacklist.count(),
                       'recordsFiltered':  blacklist.count(),
                       'draw':	context['draw'],
                       "options": {"type_blacklist": {"blacklist":"blacklist","Bounce":"Bounce"}}
            }

        return ret

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(blacklist_list, self).dispatch(*args, **kwargs)
    
 
"""

Fonction qui va uploader un fichier csv et l'enregistrer en base qui retourne le nombre de double et le nombre de données enregistrer 

""" 

def upload_file(request):
    user=User.objects.get(username=request.user) 
    cpt=0
    cpt_doublon=0
    if request.method == 'POST':
        my_file = csv.reader(request.FILES['myfile'])
        print user.id   
        for row in my_file :

           doublon,created = Blacklist.objects.get_or_create(
                email=row[0],
                type_blacklist=row[1],
                user_id=user.id , 
                )
           if(created):
              cpt=cpt+1
           if(doublon):
              cpt_doublon=cpt_doublon+1

        return  render(request, 'app/blacklist.html',{"doublon":cpt_doublon-cpt,"created":cpt})  # todo return argument 
      
    else:
      return render(request, 'app/blacklist.html')

runner/blacklist/templates/app/Chargement.html
<div class="container col-lg-10" id='wrapper'>

    <section id='sidebar'>
        {% block sidebar %}

        <i class='icon-align-justify icon-large' id='toggle'></i>
                      <div class="zoom">

  <img class="nerimLogo" src="http://www.nerim.fr/go/ultra-haut-debit/images/logo_nerim.png" alt="pensées de Giverny" />

</div>
              
        <ul id='dock'>

     
           
            <li id="dash" class='launcher active '>
                <i class='fa fa-tachometer'></i>
                <a href='{% url "dash" %}'>dashboard</a>

            </li>
            <li id="achats" class='launcher '>
                <i class='fa fa-cart-plus'></i>
                <a href='{% url "achats" %}'>achats</a>

            </li>
            <li class='launcher'>
                <i class='fa fa-cart-arrow-down '></i>
                <a href="tables.html">Ventes</a>
            </li>
            <li class='launcher dropdown hover'>
                <i class='fa fa-exclamation-triangle'></i>
                <a href='#'>Travaux</a>
            </li>
            <li class='launcher'>
                <i class='fa fa-gears '></i>
                <a href='#'>Config</a>
            </li>
            <li class='launcher'>
                <i class='fa fa-exclamation '></i>
                <a href='#'>Aide</a>
            </li>

        </ul>
        {% endblock %}

    </section>



    <section class="row">
        <ul class="breadcrumb" id="">
            <li class="title">Dashboard</li>

        </ul>
        <div id="toolbar">
            <div class="tClass btn-group">

                <a  class=" loader loader-bars" href="{% url 'admin:index' %}"></a>


            </div>

        </div>
    </section>
    <div id='content'>
        {% block content %}


        {% endblock %}

    </div>  
</div>

runner/blacklist/templates/app/base.html
{% load url from future %}
{% load account_tags %}

{% load i18n %}
{% load staticfiles %}
{% load auth %}

</html>
<head>

    <title>nerim</title>	

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">


    <!-- css  -->
    <link rel="stylesheet" type="text/css" href='{% static "reselling/css/animate.css" %}' />
    <link rel="stylesheet" type="text/css" href='{% static "reselling/css/bootstrap2.css" %}' />
    <link rel="stylesheet" type="text/css" href='{% static "reselling/css/font-awesome.css" %}' />
    <link rel="stylesheet" type="text/css" href='{% static "reselling/css/saiyan.css" %}' />
    <link rel="stylesheet" type="text/css" href='{% static "reselling/css/dataTables.tableTools.css" %}' />
    <link rel="stylesheet" type="text/css" href='{% static "reselling/css/dataTables.bootstrap.css" %}' />
    <link rel="stylesheet" type="text/css" href='{% static "reselling/css/editor.bootstrap.css" %}' />
    <link rel="stylesheet" type="text/css" href='{% static "reselling/css/dataTables.responsive.css" %}' />
    <link rel="stylesheet" type="text/css" href='{% static "reselling/css/datepicker.css" %}' />

    <!-- datatable -->
    <script src='{% static "reselling/js/jquery-1.11.1.min.js" %}'></script>
    <script src='{% static "reselling/js/jquery-ui.js" %}'></script>
    <script src='{% static "reselling/js/bootstrap.min.js" %}'></script>
    <script src='{% static "reselling/js/jquery.dataTables.min.js" %}'></script>
    <script src='{% static "reselling/js/dataTables.responsive.js" %}'></script>
    <script src='{% static "reselling/js/dataTables.tableTools.min.js" %}'></script>
    <script src='{% static "reselling/js/dataTables.editor2.js" %}'></script>
    <script src='{% static "reselling/js/dataTables.bootstrap.js" %}'></script>
    <script src='{% static "reselling/js/editor.bootstrap.js" %}'></script>

    <!-- myscriptT -->
    <script src='{% static "reselling/js/config.js" %}'></script>
    <script src='{% static "reselling/js/saiyan.js" %}'></script>

    <!-- highcharts todo telecharger highcharts-->
   <!-- highcharts todo telecharger highcharts-->
    <script src='{% static "reselling/js/highcharts.js" %}'></script>
    <script src='{% static "reselling/js/highcharts-3d.js" %}'></script>
    <script src='{% static "reselling/js/exporting.js" %}'></script>


</head>

<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div id="spinner">
            <img src='{% static "reselling/images/logo_nerim.png" %}' alt="Loading..."/>
        </div>

        {% block bar %}

        <div class="container-fluid">

            <div class="navbar-header">
                <button type="button" class="navbar-toggle  " data-toggle="collapse" data-target="#navbar" aria-expanded="true" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class='current navbar-brand' href='#'>
                    <i class='icon-beer'></i>

                    <a class="navbar-brand" href="#"></a>
                </a>
                <img class="nerimLogo" src='{% static "reselling/images/logo_nerim.png" %}' alt="pensées de Giverny" />
            </div>

            <div id="navbar"  class="collapse navbar-collapse">

                <ul class="nav navbar-nav navbar-right">


                    <form class="navbar-form navbar-right">
                        {% block connexion %}
                        {% if user.is_authenticated %}
                        {% if user.is_superuser %}
                        {% load admin_urls %}
                        <input type="text" class="form-control" placeholder="Search...">
                    </form>


                    <ul class="nav navbar-inverse navbar-nav navbar-right">
                        {% if request.user.is_authenticated %}
                        <li class="dropdown">

                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class='icon-user'></i>

                                {% user_display request.user %}
                                <img class="img-rounded" src="{% static 'reselling/images/777.gif' %}" />
                                <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">

                                <li><a href="{% url 'account_settings' %}"><i class="fa fa-user"></i> {% trans "Settings" %}</a></li>
                                {% if request.user.is_staff %}
                                <li ><a href="{% url THEME_ADMIN_URL|default:'admin:index' %}"><i class="fa fa-cog"></i> {% trans "Admin" %}</a></li>
                                {% endif %}
                                <li class="divider"></li>
                                <li>
                                    <a  data-toggle="modal" data-target="#myModal" ><i class="fa fa-power-off"></i> {% trans "Log out" %}</a>
                                </li>

                            </ul>
                        </li>
                        {% else %}
                        <li><a href="{% url 'account_login' %}">{% trans "Log in" %}</a></li>
                        {% if ACCOUNT_OPEN_SIGNUP %}
                        <li><a href="{% url 'account_signup' %}">{% trans "Sign up" %}</a></li>
                        {% endif %}
                        {% endif %}
                        {% endif %}
                    </ul>

                    <!--notif -->
                    <li class="dropdown ">
                        <a aria-expanded="true" class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-bell fa-fw"></i>  <i class="fa fa-caret-down"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-alerts">
                            <li>
                                <a href="#">
                                    <div>
                                        <i class="fa fa-comment fa-fw"></i> New Comment
                                        <span class="pull-right text-muted small">4 minutes ago</span>
                                    </div>
                                </a>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <a href="#">
                                    <div>
                                        <i class="fa fa-twitter fa-fw"></i> 3 New Followers
                                        <span class="pull-right text-muted small">12 minutes ago</span>
                                    </div>
                                </a>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <a href="#">
                                    <div>
                                        <i class="fa fa-envelope fa-fw"></i> Message Sent
                                        <span class="pull-right text-muted small">4 minutes ago</span>
                                    </div>
                                </a>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <a href="#">
                                    <div>
                                        <i class="fa fa-tasks fa-fw"></i> New Task
                                        <span class="pull-right text-muted small">4 minutes ago</span>
                                    </div>
                                </a>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <a href="#">
                                    <div>
                                        <i class="fa fa-upload fa-fw"></i> Server Rebooted
                                        <span class="pull-right text-muted small">4 minutes ago</span>
                                    </div>
                                </a>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <a class="text-center" href="#">
                                    <strong>See All Alerts</strong>
                                    <i class="fa fa-angle-right"></i>
                                </a>
                            </li>
                        </ul>
                        <!-- /.dropdown-alerts -->
                    </li>
                    <div class="modal" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">

                                <div class="modal-header">
                                    <h4 class="modal-title"> {% trans "Log out" %}</h4>
                                </div>

                                <div class="modal-body">
                                    <p>  {% trans "Etes-vous sûr de vouloir vous déconnecter?"%}</p>
                                </div>


                                <div class="modal-footer">
                                    <form method="POST" action="{% url 'account_logout' %}">
                                        <fieldset>
                                            {% csrf_token %}
                                            <button type="submit" class="btn btn-primary">{% trans "Log out" %}</button>
                                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                        </fieldset>
                                    </form>
                                </div>
                            </div>

                        </div>
                    </div>
                    {% endif %}
                    {% endblock %}
                    </div>
                </ul>
        </div>
        {% endblock %}
    </nav>



    <div class="col-lg-1">

    </div>


    <div class="container col-lg-10  ">

        <div class="row row-offcanvas row-offcanvas-left">

            <p class=" visible-xs">
                <button type="button" class="btn btn-default" aria-label="Left Align" data-toggle="offcanvas">
                    <span class="fa fa-th-list" aria-hidden="true"></span>
                </button>
            </p>
            <p class=" visible-sm">
                <button type="button" class="btn btn-default" aria-label="Left Align" data-toggle="offcanvas">
                    <span class="fa fa-th-list" aria-hidden="true"></span>
                </button>
            </p>
            <p class=" visible-md">
                <button type="button" class="btn btn-default" aria-label="Left Align" data-toggle="offcanvas">
                    <span class="fa fa-th-list" aria-hidden="true"></span>
                </button>
            </p>

       

            {% block menu %}



            {% endblock %}

            {% block content %}


            {% endblock %}
        </div>


        </body>
    </html>

runner/blacklist/templates/app/blacklist.html
{% extends 'app/base.html' %}
{% load i18n %}
{% load staticfiles %}

 
{% block content %}

<div class="col-lg-12 panel panel-default ">

    <div class="panel-heading">
        <h3 id="nomPanel" class="panel-title"></h3> 
    </div>

    <div class="panel-body">
        <div class="container col-lg-12">
 
       
            {% block content2 %}
             <form method="post" action='{% url "blacklist:csv" %}' enctype="multipart/form-data">
            {% csrf_token %}

              <div style="position:relative;">
                    <a class='btn btn-primary' href='javascript:;'>
                        Choose File...
                        <input type="file" style='position:absolute;z-index:2;top:0;left:0;filter: alpha(opacity=0);-ms-filter:"progid:DXImageTransform.Microsoft.Alpha(Opacity=0)";opacity:0;background-color:transparent;color:transparent;' name="myfile" size="40"  onchange='$("#upload-file-info").html($(this).val());'>
                    </a>
                    &nbsp;
                    <span class='label label-info' id="upload-file-info"></span>
                    <br><input class="btn" type="submit" name="submit" value="Upload" />

            </form>
            <h5> doublon : {{ doublon }} </h5>
            <h5> created : {{ created }} </h5>
 
            
            <div id="ref" class=" col-lg-12">
                <h1 class="visible-lg  text-center">Application blacklist</h1>      
                <h2 class="visible-xs  text-center">Application blacklist</h2>      
                <p>......Rajouter , supprimer , modifier vos blacklist.......</p>    

                <div class="col-lg-12" id="example2"></div>

            </div>
            {% endblock %}

        </div> 
    </div>
</div>

<div class="col-lg-1"></div>


<script>

    datatableSaiyan( {
        "idsaiyan": "example2",
        "urldata": "/blacklist/jsonblacklist_list/",
        "urlrest": "/api/juridt",
        "dom": "Tfrtip",
        "col": "12",
        "fields": [
         {
                "label": "type:",
                "name": "type_blacklist",
                "type": "radio"
            },

            {
                "label": "email:",
                "name": "email"
            }
           ,

        ]
    }
     )
  

</script>



{% endblock %}